
version: 2

models:
  - name: order_fact
    columns: 
      - name: order_id
        tests:
          - not_null
      - name: order_cost
        tests:
          - not_null
          - positive_values

  - name: agg_order_location_fact

  - name: intermediate_products_ordered
    columns: 
      - name: order_id
        tests:  
          - not_null
      - name: name
        tests:
          - not_null

  - name: intermediate_user_location

  - name: session_fact

  - name: user_orders_fact

  - name: intermediate_event_actions

  - name: products_sold_monthly
  
  - name: products_sold
